apiVersion: v1
kind: Service
metadata:
  name: chain33-subdomain
  labels:
    app: chain33
  namespace: default
spec:
  selector:
    app: chain33
  clusterIP: None
  ports:
  - name: jrpc # 实际上不需要指定端口号
    protocol: TCP
    port: 8801
    targetPort: 8801
  - name: grpc # 实际上不需要指定端口号
    protocol: TCP
    port: 8802
    targetPort: 8802


